FROM python:3.11

RUN pip install --upgrade pip setuptools

RUN apt update

ARG UID=1000

RUN useradd -u $UID -m -s /bin/bash ubuntu

WORKDIR /home/ubuntu/lil_bro

COPY --chown=ubuntu:ubuntu req.txt .

RUN pip install -r req.txt

RUN mkdir static media && chown -R ubuntu:ubuntu /home/ubuntu/lil_bro && chmod -R 755 /home/ubuntu/lil_bro

COPY --chown=ubuntu:ubuntu . .

USER ubuntu

