services:
  lil_bro_app:
    container_name: lil_bro_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: |
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn -c config/gunicorn_config.py config.wsgi:application"
    tty: false
    volumes:
      - ./static:/lil_bro/static:rw
      - ./media:/lil_bro/media:rw
      - letsencrypt:/etc/letsencrypt:rw
      - .:/lil_bro:rw
    restart: on-failure
    env_file:
      - .env
    expose:
      - '8000'
    depends_on: [lil_bro_db, redis, celery, beat]

  lil_bro_db:
    container_name: database
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - lil_bro_db:/var/lib/postgresql/data:rw

  celery:
    container_name: celery-worker
    build:
      context: .
    restart: on-failure
    depends_on: [redis]
    command: sh -c "celery -A config worker -l info -S django"

  beat:
    container_name: celery-beat
    build:
      context: .
    restart: on-failure
    depends_on: [celery]
    command: sh -c "celery -A config beat -l info -S django"

  redis:
    container_name: redis
    image: redis:6.0.16-alpine
    hostname: redis
    depends_on: [lil_bro_db]

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    container_name: nginx
    volumes:
      - .:/lil_bro
      - ./static:/lil_bro/static:ro
      - ./media:/lil_bro/media:ro
      - letsencrypt:/etc/letsencrypt:ro
    depends_on: [lil_bro_app]
    ports:
      - '${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}'
      - '${NGINX_EXTERNAL_PORT_S}:${NGINX_INTERNAL_PORT_S}'
    restart: on-failure

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt:rw
      - .:/lil_bro
    command: certonly --webroot --webroot-path=/lil_bro --email zhorikzeniuk@gmail.com --agree-tos --no-eff-email --force-renewal -d thelilbro.xyz
  

volumes:
  letsencrypt:
  lil_bro_db:
    driver: local
