# Generated by Django 4.2.8 on 2023-12-26 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_phrase', models.CharField(blank=True, max_length=64, null=True, verbose_name='code_phrase')),
                ('secret_text', models.TextField(verbose_name='secret text')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='link')),
                ('lifetime', models.PositiveSmallIntegerField(verbose_name='lifetime')),
                ('is_code_phrase', models.BooleanField(default=False)),
                ('time_to_delete', models.DateTimeField(blank=True, null=True, verbose_name='time to delete')),
            ],
            options={
                'verbose_name': 'secret',
                'verbose_name_plural': 'secrets',
            },
        ),
    ]
