# Generated by Django 4.2.8 on 2023-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lil_bro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='code_phrase',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='code_phrase'),
        ),
    ]
