# Generated by Django 4.2.8 on 2023-12-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lil_bro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='is_code_phrase',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='link',
        ),
    ]
