# Generated by Django 4.2.8 on 2024-10-12 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lil_bro', '0002_remove_secret_is_code_phrase_remove_secret_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='sreated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
