# Generated by Django 4.2.8 on 2024-10-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lil_bro', '0003_secret_sreated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='sreated_by',
            new_name='сreated_by',
        ),
    ]
