# Generated by Django 4.2.8 on 2024-10-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lil_bro', '0004_rename_sreated_by_secret_сreated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='сreated_by',
            new_name='created_by',
        ),
    ]
